using Terrajobst.UsageCrawling.Collectors;
using Terrajobst.UsageCrawling.Tests.Infra;

namespace Terrajobst.UsageCrawling.Tests.Collectors;

public class ApiUsageCollectorTests : CollectorTest<ApiUsageCollector>
{
    // Note: We don't need to deep here, most of the API specific tests are against the underlying AssemblyCrawler

    [Fact]
    public void ApiUsageCollector_Reports_MethodCalls()
    {
        var source =
            """
            using System;
            public class C {
                public static object M(string s) {
                    return s.Substring(s.Length);
                }
            }
            """;

        var expectedIds =
            """
            M:System.Object.#ctor
            T:System.String
            M:System.String.Substring(System.Int32)
            M:System.String.get_Length
            """;

        Check(source, expectedIds);
    }

    private void Check(string source, string expectedIds)
    {
        Check(source, expectedIds, FeatureUsage.ForApi);
    }

    protected override bool Include(FeatureUsage featureUsage)
    {
        if (featureUsage.Argument is not string documentationId)
            return true;

        return !AssemblyBuilder.IsAutoGenerated(documentationId);
    }
}